name: Typecheck
on: [push, pull_request]
jobs:
  lint:
    name: Type checks the code
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Typecheck code
        run: pnpm typecheck
